# Killer Cell Immunoglobulin-like Receptors {.unnumbered}

## Background

KIR is located on chromosome 19 (19q13.4) in the Leukocyte Receptor Complex (LRC). KIR is expressed on the surface of Natural Killer (NK) cells and some T cells. KIR do not undergo somatic rearrangement--a key difference from T-cell receptors. KIR interacts with HLA class I--their cognate ligand--to recognize and destroy unhealthy tissue cells while preventing the same from occurring to healthy cells. Therefore, NK cells play a role in fighting infections, resisting some cancers, pregnancy, and preventing autoimmunity. For further reading and references, I highly recommend the review article by Pollock, Harrison, and Norman on the immunogenetics and co-evolution of KIR and HLA class I.

## KIR Locus

<table>
<caption>Adapted from <a href="https://doi.org/10.1016/j.jaip.2022.04.036"><em>Pollock, Harrison, and Norman. JACI: In Practice. 2022.</em></a></caption>
<colgroup>
<col style="width: 10%" />
<col style="width: 10%" />
<col style="width: 10%" />
<col style="width: 10%" />
<col style="width: 10%" />
<col style="width: 10%" />
<col style="width: 10%" />
<col style="width: 10%" />
<col style="width: 10%" />
<col style="width: 10%" />
<col style="width: 10%" />
<col style="width: 10%" />
<col style="width: 10%" />
<col style="width: 10%" />
<col style="width: 10%" />
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;"><p><strong>Gene</strong></p></th>
<th style="text-align: center;"><p><strong>3DL3</strong></p></th>
<th style="text-align: center;"><p><strong>2DS2</strong></p></th>
<th style="text-align: center;"><p><strong>2DL2/3</strong></p></th>
<th style="text-align: center;"><p><strong>2DL5B</strong></p></th>
<th style="text-align: center;"><p><strong>2DS3</strong></p></th>
<th style="text-align: center;"><p><strong>2DL1</strong></p></th>
<th style="text-align: center;"><p><strong>2DL4</strong></p></th>
<th style="text-align: center;"><p><strong>3DL1</strong></p></th>
<th style="text-align: center;"><p><strong>3DS1</strong></p></th>
<th style="text-align: center;"><p><strong>2DL5A</strong></p></th>
<th style="text-align: center;"><p><strong>2DS5</strong></p></th>
<th style="text-align: center;"><p><strong>2DS4</strong></p></th>
<th style="text-align: center;"><p><strong>2DS1</strong></p></th>
<th style="text-align: center;"><p><strong>3DL2</strong></p></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><p><strong>Function</strong></p></td>
<td style="text-align: center;"><p>Inhibit.</p></td>
<td style="text-align: center;"><p>Activ.</p></td>
<td style="text-align: center;"><p>Inhibit.</p></td>
<td style="text-align: center;"><p>Inhibit.</p></td>
<td style="text-align: center;"><p>Activ.</p></td>
<td style="text-align: center;"><p>Inhibit.</p></td>
<td style="text-align: center;"><p>Activ.</p></td>
<td style="text-align: center;"><p>Inhibit.</p></td>
<td style="text-align: center;"><p>Activ.</p></td>
<td style="text-align: center;"><p>Inhibit.</p></td>
<td style="text-align: center;"><p>Activ.</p></td>
<td style="text-align: center;"><p>Activ.</p></td>
<td style="text-align: center;"><p>Activ.</p></td>
<td style="text-align: center;"><p>Inhibit.</p></td>
</tr>
<tr class="even">
<td style="text-align: center;"><p><strong>Alleles</strong></p></td>
<td style="text-align: center;"><p>228</p></td>
<td style="text-align: center;"><p>65</p></td>
<td style="text-align: center;"><p>98</p></td>
<td style="text-align: center;"><p>47</p></td>
<td style="text-align: center;"><p>71</p></td>
<td style="text-align: center;"><p>173</p></td>
<td style="text-align: center;"><p>112</p></td>
<td style="text-align: center;"><p>184</p></td>
<td style="text-align: center;"><p>39</p></td>
<td style="text-align: center;"><p>44</p></td>
<td style="text-align: center;"><p>88</p></td>
<td style="text-align: center;"><p>39</p></td>
<td style="text-align: center;"><p>33</p></td>
<td style="text-align: center;"><p>166</p></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><p><strong>Allotypes</strong></p></td>
<td style="text-align: center;"><p>112</p></td>
<td style="text-align: center;"><p>22</p></td>
<td style="text-align: center;"><p>50</p></td>
<td style="text-align: center;"><p>21</p></td>
<td style="text-align: center;"><p>23</p></td>
<td style="text-align: center;"><p>65</p></td>
<td style="text-align: center;"><p>58</p></td>
<td style="text-align: center;"><p>92</p></td>
<td style="text-align: center;"><p>22</p></td>
<td style="text-align: center;"><p>19</p></td>
<td style="text-align: center;"><p>38</p></td>
<td style="text-align: center;"><p>20</p></td>
<td style="text-align: center;"><p>12</p></td>
<td style="text-align: center;"><p>115</p></td>
</tr>
<tr class="even">
<td style="text-align: center;"><p><strong>HLA<br />
Class I Ligand Motifs</strong></p></td>
<td style="text-align: center;"><p>B7H7</p></td>
<td style="text-align: center;"><p>A*11<br />
C1</p></td>
<td style="text-align: center;"><p>B*46:01<br />
B*73:01<br />
C1<br />
C2</p></td>
<td style="text-align: center;"><p>PVR</p></td>
<td style="text-align: center;"><p>?</p></td>
<td style="text-align: center;"><p>C2</p></td>
<td style="text-align: center;"><p>HLA-G</p></td>
<td style="text-align: center;"><p>Bw4+<br />
HLA-A and Bw4+ HLA-B</p></td>
<td style="text-align: center;"><p>Bw4+<br />
HLA-B and<br />
HLA-F</p></td>
<td style="text-align: center;"><p>PVR</p></td>
<td style="text-align: center;"><p>C2</p></td>
<td style="text-align: center;"><p>A*11<br />
HLA-C</p></td>
<td style="text-align: center;"><p>C2</p></td>
<td style="text-align: center;"><p>A*3<br />
A*11</p></td>
</tr>
</tbody>
</table>

: Adapted from [*Pollock, Harrison, and Norman. JACI: In Practice. 2022.*](https://doi.org/10.1016/j.jaip.2022.04.036)

## KIR Diversity

KIR diversity is influenced by gene content variation and sequence variation. Distinct DNA sequences of KIR genes are called "alleles." Distinct polypeptide sequences of KIR genes are called "allotypes." Because different DNA sequences of KIR gene can lead to the same polypeptide, there are more alleles than allotypes for a given KIR gene.

+------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+
| KIR Diversity Concept  | Definition                                                                                                                                                     |
+:======================:+:==============================================================================================================================================================:+
| Gene Content Variation | Presence/absence, fusion, duplication                                                                                                                          |
+------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Sequence Variation     | May alter ligand affinity or specificity, signal transduction ability, or surface expression (e.g., promoter activity, translation, intracellular trafficking) |
+------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Allele                 | Distinct DNA sequence                                                                                                                                          |
+------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Allotype               | Distinct polypeptide sequence                                                                                                                                  |
+------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+

## NK Cell Education

+---------------------------+----------------------------------------------------+-------------------------------------------+
| NK Cell Education\        | Corresponding Pairs of KIR and HLA Class I Ligands | Cytotoxicity and other Effector Abilities |
| (i.e., Arming, Licensing) |                                                    |                                           |
+:=========================:+:==================================================:+:=========================================:+
| Strong                    | Many                                               | More                                      |
+---------------------------+----------------------------------------------------+-------------------------------------------+
| Weak                      | Few                                                | Less                                      |
+---------------------------+----------------------------------------------------+-------------------------------------------+

## KIR Nomenclature

### Inhibitory KIR

The main role of inhibitory KIR is to prevent cytotoxic NK and T cells from killing tissue cells--unless their HLA class I expression is lost or altered by infection or mutagenesis.

### Activating KIR

Activating KIR help identify diseased cells for destruction by cytoxic NK and T cells. Binding of foreign peptides by HLA class I molecules retained by infected cells may be most critical for activating KIR.

### Broad KIR Haplotypes

+---------------------+---------------------------+-----------------------+----------------+
| Broad KIR Haplotype | KIR Copy Number Variation | KIR Gene Organization | Activating KIR |
+:===================:+:=========================:+:=====================:+:==============:+
| A                   | Relatively stable         | Generally\            | Less           |
|                     |                           | non-variable          |                |
+---------------------+---------------------------+-----------------------+----------------+
| B                   | Extensive                 | Highly variable       | More           |
+---------------------+---------------------------+-----------------------+----------------+

## KIR Ligand Motifs

+------------------+-------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------+
| KIR Ligand Motif | HLA-A Allotypes                                                                                             | HLA-B Allotypes                                                                                                                                                         | HLA-C Allotypes                                                          |
+:================:+:===========================================================================================================:+:=======================================================================================================================================================================:+:========================================================================:+
| A3/A11           | A\*03, A\*11                                                                                                | ------------------------------------------------------------------------                                                                                                | ------------------------------------------------------------------------ |
+------------------+-------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------+
| Bw4              | A\*23, A\*24, A\*32                                                                                         | B\*07:27, B\*08:02, B\*08:03, (B13), B\*15:13, B\*15:16, B\*15:17, B\*15:23, B\*15:24, B\*15:36, B\*15:43, B\*15:67, B\*27:01, B\*27:02, B\*27:03, B\*27:04, B\*27:05,\ | ------------------------------------------------------------------------ |
|                  |                                                                                                             | B\*27:07, B\*37, B\*38, B\*40:13, B\*40:19, B\*44, B\*47, B\*49, B\*51, B\*52, B\*53, B\*56:07, B\*57, B\*58, B\*59                                                     |                                                                          |
+------------------+-------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------+
| C1               | C\*01, C\*03, C\*07, C\*08, C\*12:02, C\*12:03, C\*12:06, C\*12:08, C\*13, C\*14, C\*16                     | B\*46, B\*73                                                                                                                                                            | ------------------------------------------------------------------------ |
+------------------+-------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------+
| C2               | C\*02, C\*03:07, C\*04, C\*05, C\*06, C\*12:04, C\*12:05, C\*12:07, C\*14:04, C\*15, C\*16:02, C\*17, C\*18 | ------------------------------------------------------------------------                                                                                                | ------------------------------------------------------------------------ |
+------------------+-------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------+

: Adapted from [*Pollock, Harrison, and Norman. JACI: In Practice. 2022.*](https://rstudio.tbilab.org/s/062495e2502154914bf19/?launcher=1#0)

## KIR3DL1 and KIR3DS1

Because of significant non-allelic recombination in the KIR region, the distinction between KIR genes and alleles can be confusing. Specifically, KIR3DL1 and KIR3DS1 are alleles of the same gene. Of the KIR3DS1 allotypes--3DS1*013 and* 014--are observed with the greatest frequency in any population.