---
execute:
  echo: false
  message: false
  warning: false
---

# On Being a Physician-Scientist {.unnumbered}

## Building Accountability

### Semester Plan by Week

Every Friday, you should schedule yourself 30 minutes to plan your next week. Weekly Planning meeting 30 minutes. If wait you wait until Monday, you won't start your week with momentum. 3 hours/deep work per day.

1 - Reflect on the prior week and how you did

2 - Set up skeleton for week (5 min)

-   Write/Design/Analysis in Mornings

-   Meetings in Afternoon

3 - Brain dump of things to get done; Map steps (15 min)

4 - Tasks meet time (10 min)

You should keep and update your semester plan. Here is a link to an NCFDD example.

::: callout-important
We drastically underestimate how long research and writing tasks will take. Multiplying your initial estimate by 1.5x - 2.5x might get you closer to realistically how long a particular task will take.
:::

### Task Tracking

Don't need to track every last minute/hour. Just track the "deep work" hours. Cal Newport, Deep Work.

Harvest Time app. Link to website.

Freedom - block email during "deep work" time.

### Mentor Meetings

Could also be a peer.

Have an agenda and take notes for the meeting.

## Daily Writing Practice

Why is it that the most important academic activity for tenure, promotion, and professional reputation—writing—has the least amount of built-in accountability?

If you are a physician-scientist, you are a writer; therefore, you should write everyday (Monday - Friday).

+:------------:+:-----------------------------------------------------------------:+:-------------------:+
| *Less*       | **Built-in accountability**                                       | *More*              |
+--------------+-------------------------------------------------------------------+---------------------+
| -   Writing  | **-\>**                                                           | -   Service         |
|              |                                                                   |                     |
| -   Articles | **Activity**                                                      | -   Teaching        |
|              |                                                                   |                     |
| -   Grants   | **\<-**                                                           | -   Clinic/Consults |
+--------------+-------------------------------------------------------------------+---------------------+
| *More*       | **Importance for tenure, promotion, and professional reputation** | *Less*              |
+--------------+-------------------------------------------------------------------+---------------------+

: Built-in accountability and importance for tenure, promotion, and professional reputation by activity {#tbl-accountability-importance}

::: callout-note
The most important part of your promotion—writing—has the least accountability.
:::

+------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------+
| Belief                                         | Reality                                                                                                                                 |
+:==============================================:+:=======================================================================================================================================:+
| "I need huge blocks of time."                  | "*Both unrealistic and untrue.* You can productively write in 30 minute blocks!"                                                        |
+------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------+
| "I must be inspired to write."                 | "*No, you don't.* If you put it on your calendar, you can show up to write just like you show up to meetings you don't want to attend." |
+------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------+
| "Writing is what I do when I'm done thinking." | "*Writing is thinking.*"                                                                                                                |
+------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------+

: Limiting beliefs to cultivating a daily writing practice. Adapted from NCFDD. {#tbl-writing-beliefs}

### Research on Daily Writing

+------------------------------------------------------+------------------------------+
| Participant Groups                                   | Draft Pages Written per Year |
+======================================================+==============================+
| No change                                            | 17                           |
+------------------------------------------------------+------------------------------+
| Wrote daily and recorded progress                    | 64                           |
+------------------------------------------------------+------------------------------+
| Wrote daily, recorded progress, and were accountable | 157                          |
+------------------------------------------------------+------------------------------+

: Adapted from @boice1989 {#tbl-research-daily-writing-boice}

### Time Target for Daily Writing

Your goal should be to spend 3 or more hours per week on scholarly writing. So, if you write 30 minutes Monday to Friday, you are already at 2.5 hours!

### Tips for Daily Writing

Schedule your writing in your calendar like any other meeting or clinical duty.

You should write first thing in the morning. Knock out the most important daily task for your career first!

Map complex goals to attainable steps.

Use a timer, stop when the timer goes off (to avoid slipping back into writing in huge chunks).

Leave yourself a "breadcrumb," so you can pick up where you left off.

Give yourself a treat after writing.

Do a reflection at the end of the week (Friday) on how your writing went.

### Benefits of Daily Writing

Writing daily helps align your time with your evaluation criteria (e.g. 80% research and 20% clinical).

+--------------------+----------------------------------------------------------------------------------------------------+
| Benefit            | Description                                                                                        |
+====================+====================================================================================================+
| Productivity Shift | Leads to slow, steady productivity and fewer feelings of anxiety over meeting writing expectations |
+--------------------+----------------------------------------------------------------------------------------------------+
| Mental Shift       | Writing is the most important part of your success; therefore, it is your top priority.            |
+--------------------+----------------------------------------------------------------------------------------------------+
| Behavior Shift     | You write everyday and find a way to be accountable that works for you!                            |
+--------------------+----------------------------------------------------------------------------------------------------+

: Benefits of daily writing. Adapted from NCFDD {tbl-benefits-daily-writing}

## Academic Medicine Jobs

### AAMC Faculty Salary Report

Looking to get an idea of academic faculty salaries? The annual [AAMC Faculty Salary Report](https://www.aamc.org/data-reports/workforce/report/aamc-faculty-salary-report) compiles academic faculty salaries by rank, degree, department/specialty, medical school type, region, and more. This is often available for free through your university library. Get to know your librarian!

### Tenure-Track Offer Letters

What goes into a tenure-track offer letter? The [Burroughs Wellcome Fund](https://www.bwfund.org/) provides a comprehensive list of offer letter components in their article, "[Academic Tenure-Track Offer Letters](https://www.bwfund.org/career-tool/academic-tenure-track-offer-letters/)."

## NIH Career Development Awards

The NIH provides [Success Rates](https://report.nih.gov/funding/nih-budget-and-spending-data-past-fiscal-years/success-rates) for Career Development Awards. Below, you will find interactive plots for Fiscal Years 2014-2023 and can analyze success rates by individual institute or by all for the primary extramural, mentored career development awards (K01, K08, K23, K99). These interactive plots were created using [Observable JS](https://quarto.org/docs/computations/ojs.html). You can download the publicly available [dataset](https://report.nih.gov/reportweb/web/displayreport?rId=551) from the NIH. You can also find a copy in the [data folder](https://github.com/mattkrantz/tb4i/tree/main/data/on-being-a-physician-scientist) of this book's GitHub repository.

```{r}
library(readxl)
library(dplyr)
library(here)

dat = read_excel(here("data/on-being-a-physician-scientist", "T204 2023 CAREER DEV_Appls_Awds_Succ Rate_Fund by Act and IC.xlsx"), skip=1, sheet=1) %>% 
  rename(
    fiscal_year=`Fiscal Year`,
    activity_code=`Activity Code`,
    nih_institute=`NIH Institute / Center`,
    n_applications=`Number of Applications Reviewed`,
    n_awarded=`Number of Applications Awarded`,
    success_rate=`Success Rate`,
    total_funding=`Total Funding`) %>%
  mutate(nih_institute = if_else(nih_institute == "ACTIVITY TOTAL", "All", nih_institute))

ojs_define(data_json = dat)

```

### Interactive Plots

```{ojs}

data = transpose(data_json)

nih_institutes = ["NCI", "NEI", "NHLBI", "NHGRI", "NIA", "NIAAA", "NIAID", "NIAMS", "NIBIB", "NICHD", "NIDCD", "NIDCR", "NIDDK", "NIDA", "NIEHS", "NIGMS", "NIMH", "NIMHD", "NINDS", "NINR", "NLM"]

viewof selected_nih_institute = Inputs.select(["All"].concat(nih_institutes), {label: "NIH Institute"})

viewof activity_codes = Inputs.checkbox(
  ["K01", "K08", "K23", "K99"], 
  { value: ["K08", "K01", "K23", "K99"], 
    label: "Activity Code:"
  }
)

filtered = data.filter(function(d) {
  return activity_codes.includes(d.activity_code) && d.nih_institute === selected_nih_institute;
})
html`<br>`
html `<div style="text-align: center; font-weight: bold;"> Success Rates by Fiscal Year </div>`

plt1 = Plot.plot({
  color: {legend: true, label: "Activity Code"},
  marks: [
    Plot.lineY(filtered, {x: "fiscal_year", y: "success_rate", 
    stroke: "activity_code", 
    channels: {
      n_awarded: {value: "n_awarded", label: "No. Awarded"},
      n_applications:{value: "n_applications", label: "No. Applications"}},
    tip: {
      format: {x:"d", z:false, y: d3.format(",.0%")}}})
    ],
    style: {fontSize: "11px"},
    x: {label: "Fiscal Year", tickFormat: d3.format("d")},
    y: {label: "Success Rate", tickFormat: d3.format(",.0%")}
    })

html `<div style="text-align: center; font-weight: bold;"> Applications by Fiscal Year </div>`
plt2 = Plot.plot({
  color: {legend: true, label: "Activity Code"},
  marks: [
    Plot.barY(filtered, {x: "fiscal_year", y: "n_applications", fill: "activity_code", tip: {format: {x:"d"}}})
    ],
    x: {label: "Fiscal Year", tickFormat: "d"},
    y: {label: "No. of Applications"},
    fill: {label: "Activity Code"},
    style: {fontSize: "11px"}
    })
    
    

```

## NIH Loan Repayment Program

[NIH Loan Repayment Program](https://www.lrp.nih.gov)

## Online Resources

### Edge for Scholars

[Edge for Scholars](https://edgeforscholars.org)

### Nature Masterclasses

[Nature Masterclasses](https://masterclasses.nature.com/)

### National Center for Faculty Development and Diversity

The National Center for Faculty Development and Diversity ([NCFDD](https://www.ncfdd.org)) provides practical resources for academic researchers. I recommend signing up for their Monday Motivator Newsletter and watching their Core Curriculum videos.

## Professional Organizations

[American Physician Scientists Association](https://www.physicianscientists.org)

## Peer Review

+-------------------------+-------------------------------------------------------------------------+
| Type                    | Description                                                             |
+=========================+=========================================================================+
| Single Blind            | -   Peer reviewers not known to authors but peer reviewers see authors  |
|                         |                                                                         |
|                         | -   Peer review reports not published                                   |
+-------------------------+-------------------------------------------------------------------------+
| Double Blind            | -   Both authors and peer reviewers are not identified                  |
+-------------------------+-------------------------------------------------------------------------+
| Open (i.e. Transparent) | -   The peer review reports and identities are published with the paper |
+-------------------------+-------------------------------------------------------------------------+

Peer review is not quick or easy. It takes hours over a period of time to do well.

Goal: Give constructive feedback to peer researchers in a professional tone that includes both the strengths and weakness of their work.

Benchmark to Shoot for: Review 3 papers for every paper you submit or review \~1 paper per month

Reasons to Peer Review:

Service to scientific community

Teach trainees by co-reviewing with

Build researcher profile and CV (ORCID, Web of Science) to record/get credit for peer review activity

Steps for Peer Review

Before Accepting Peer Review

Am I qualified?

Do I have any conflicts?

Do I have time?

Doing the Peer Review

Before Starting the Peer Review

Is their a submission form with questions? Is this a narrative or structured review

Step 1: Initial Read through Paper

-   Read through the whole manuscript to get an overall impression of the study. Maybe jot down a few notes but not much.

-   Questions to think about:

    -   What is the research question?

    -   Is the question answered?

    -   Does the data support the claims?

    -   Novelty? Appropriate for the journal/would readers be interested in the study?

    -   Study design appropriate?

    -   Any fundamental flaws?

    -   Strong methodological rigor?

Step 2: Put paper aside for a couple of days

Step 3: Detailed read through and content analysis (major comments)

-   Make notes in a separate document and note the line \#

Step 4: Readability analysis (minor comments)

-   Make notes in a separate document and note the line \#

-   Logical flow/structure

-   This is not about spelling and grammar. Don't worry about this unless it causes major issues with readability. The paper will be copy edited if accepted for publicatin.

Step 5: Write the summary statement of paper and thoughts on suitable for publication.

-   Does not need to be long

-   Helps the authors know you too the time to understand their study and the editors know what you think about it.

-   1st part of the report

Structure of Peer Review Report

[Peer Review Template](https://github.com/mattkrantz/tb4i/blob/main/templates/peer-review-template.docx)

Summary statement

Major comments

Minor comments

Comments to Editor Box

-   Potential COI

-   Acknowledge any trainees that co-reviewed with

## Suggested Readings

### Not Discussed

[Not Discussed](https://www.amazon.com/Not-Discussed-unspoken-academic-research/dp/172162502X) by Michael SteinPublishing Your Medical Research

[Publishing Your Medical Research](https://www.amazon.com/Publishing-Medical-Research-Daniel-Byrne/dp/1496353862/ref=sr_1_1?crid=3F5BP25U9CE6I&dib=eyJ2IjoiMSJ9.REkf1mtiHjg8wQYHq-l_uM1mEnpISI9prYug5IUDsYjJEeqL4_dS21DlCngkbglNM0Ta-DYibacy7sXoOtMobP3CMl_U-YcxcRLmnwC29OoQ5S83qHoUDJxOKCVlITpks080TU8upjIyC6K0Qh-BzLc4XKdRjrM8nzpXqPJGZhHv4pHqsmprjFjvtHQtJvQH40uSWxRjZ2sk8jOdJmxmONRkqBWyTO1P2-yi_fa83zc.MXpIhKTk-4zMTbBXRuntFhP6guiUi5Mcmd5Vpmsk7PE&dib_tag=se&keywords=publishing+your+medical+research&qid=1721136315&s=books&sprefix=publishing+your+medical+research%2Cstripbooks%2C92&sr=1-1) by Daniel W. Byrne

Deep Work by Cal Newport

## Motivating Quotes

Beauty is in the edit (Prof G)

If it's your job to eat a frog, it's best to do it first thing in the morning. And If it's your job to eat two frogs, it's best to eat the biggest one first. - Twain

DRY WIT

Action absorbs anxiety

Improv Edit when the scene needs to be edited, then figure out what to do

Separate the creativity from the execution (BJ Novak) Right down funny ideas when you think of them so that you can come back to later during the execution

Put your self in situations where luck can happen
