# Project Organization

If you would like a video overview of how to organize a project using R Studio, I recommend [Ming "Tommy" Tang](https://tommytang.bio.link)'s tutorial on YouTube, "[How to Organize a Computational Biology Project](https://www.youtube.com/watch?v=wXXhp9sXqao)". In his tutorial he references an excellent reference on project organization, "[A Quick Guide to Organizing Computational Biology Projects](https://journals.plos.org/ploscompbiol/article?id=10.1371%2Fjournal.pcbi.1000424)" by @noble2009.

::: callout-note
In RStudio, you should create a "New Project," which creates both a project folder and a .Rproj file (which sets the path for your project working directory). You should use the [`here`](https://here.r-lib.org) package to easily build paths to files in a more reliable fashion than using [setwd()](https://rdrr.io/r/base/getwd.html).
:::

**Bash Commands to Create Folder Directory Structure for Your R Project**

Once you have created your New Project in RStudio and are in `your-r-project-folder` in the Terminal. You can create your `README.md` file and your sub-folder directory structure.

``` bash
touch README.md
mkdir data doc scripts bin outputs
```

Once you have downloaded your raw data to your data folder, you should make the contents of the data folder read-only (non-editable) with the following command: `chmod u-w -R data/`
